#!/bin/bash

## -------------------------------------------------------------------
## 4CHAN image downloader 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Downloads all pictures in a 4CHAN thread.
### Usage: 4chanDownload [options] <url>
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

. $(dirname $0)/scriptsConfig

LOC=$(echo "${args[<url>]}" | egrep -o '\/thread\/[0-9]+' | egrep -o '[0-9]+' )
echo "Downloading to $CHANPICTUREDIR/$LOC"

if [ ! -d $CHANPICTUREDIR/$LOC ]; then
    mkdir $CHANPICTUREDIR/$LOC
fi

cd $CHANPICTUREDIR/$LOC

while [ "1" = "1" ]; do
    TMP=`mktemp`
    TMP2=`mktemp`

    wget -O "$TMP" "${args[<url>]}"
    if [ "$?" != "0" ]; then
        rm $TMP $TMP2
        exit 1
    fi

    egrep '//i\.4cdn\.org/[a-zA-Z0-9]+/[0-9A-Za-z]+\.(jpg|png|gif)' "$TMP" -o > "$TMP2"
    cat "$TMP2" | sed 's/\/\//http:\/\//g' > "$TMP"

    wget -nc -i $TMP
 
    rm $TMP $TMP2
 
    echo "Waiting 15 seconds before next run"
    sleep 15
done;
