#!/bin/bash

if [ "$1" = "" ]; then
	echo "Usage: `basename $0` <4chan thread url>"
	exit 1
fi

. $(dirname $0)/scriptsConfig


echo "4chan downloader"
echo "Downloading until canceled or 404'd"
LOC=$(echo "$1" | egrep -o '([0-9]*)$' )
echo "Downloading to $CHANPICTUREDIR/$LOC"

if [ ! -d $CHANPICTUREDIR/$LOC ]; then
	mkdir $CHANPICTUREDIR/$LOC
fi

cd $CHANPICTUREDIR/$LOC

while [ "1" = "1" ]; do
	TMP=`mktemp`
	TMP2=`mktemp`

	wget -O "$TMP" "$1"
	if [ "$?" != "0" ]; then
		rm $TMP $TMP2
		exit 1
	fi

	egrep '//images.4chan.org/[a-z0-9]+/src/([0-9]*).(jpg|png|gif)' "$TMP" -o > "$TMP2"
	cat "$TMP2" | sed 's/\/\//http:\/\//g' > "$TMP"

	wget -nc -i $TMP
 
	rm $TMP $TMP2
 
	echo "Waiting 15 seconds before next run"
	sleep 15
done;
