#!/bin/bash

## -------------------------------------------------------------------
## Screen brightness increaser 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Increases screen brightness by 1 (how much that does will vary)
### Usage: brightnessUp
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

/opt/extras.ubuntu.com/indicator-brightness/indicator-brightness-adjust --up
