#!/bin/bash

## -------------------------------------------------------------------
## Background Changer 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Changes the background to a random image in the directory specified in the config file.
### Usage: changeBackground [options]
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

. $(dirname $0)/scriptsConfig

THEFILE=$(ls $WALLPAPERSDIR |sort -R |tail -n 1)
hsetroot -fill $WALLPAPERSDIR/$THEFILE
