#!/bin/bash

## -------------------------------------------------------------------
## Disk Unmounter 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Unmounts the disk with the given label.
### Usage: gitAddUpdateIgnore [options] <label>
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

DRIVE=$(echo ${args[<label>]} | sed 's/ /\\x20/g')

udisks --unmount /dev/disk/by-label/$DRIVE
