#!/bin/bash

. $(dirname $0)/git-sh-prompt
. $(dirname $0)/scriptsConfig

REPODIR=$(echo $(cd "$(__gitdir)/.."; pwd) | tr / \\n | tail -1)

if [[ -n $REPODIR ]]; then
    if [[ ! -e $GITDIR/.autoUpdateIgnore ]]; then touch $GITDIR/.autoUpdateIgnore; fi
    if [[ -z $(cat $GITDIR/.autoUpdateIgnore | egrep "\b$REPODIR\b") ]]; then
        echo $REPODIR >> $GITDIR/.autoUpdateIgnore
        echo -e "\e[36mAdded $REPODIR to the git update ignore list.\e[m"
        exit 0
    else
        echo -e "\e[31mERROR: This repository is already being ignored.\e[m"
        exit 1
    fi
else
    echo -e "\e[31mERROR: Not within a git repository.\e[m"
    exit 2
fi
