#!/bin/bash

. $(dirname $0)/git-sh-prompt
. $(dirname $0)/scriptsConfig

cd $GITDIR

for FILE in `ls`; do
    if [ -d $FILE ]; then
        cd $FILE

        GITSTATUS=$(git status 2>/dev/null)

        if [[ "$GITSTATUS" != *"nothing to commit, working directory clean" ]]; then
                echo -e "\e[36m$FILE\e[m has \e[31muncommitted changes\e[m."
        fi

        for REMOTE in `git remote`; do
            for BRANCH in `git branch | sed s/"*"//g`; do
                if [[ -n $(git log $REMOTE/$BRANCH..$BRANCH) ]]; then
                    echo -e "\e[36m$FILE\e[m needs \e[31m$BRANCH\e[m to be pushed to \e[31m$REMOTE\e[m."
                fi
                if [[ -n $(git log $BRANCH..$REMOTE/$BRANCH) ]]; then
                    echo -e "\e[36m$FILE\e[m needs \e[31m$BRANCH\e[m to be merged from \e[31m$REMOTE\e[m."
                fi
            done
        done
       
        cd ..
    fi
done
