#!/bin/bash

. $(dirname $0)/scriptsConfig

QUIET=0
REMOTE=""
DOIGNORE=0
IGNORES=""
for ARG in $@; do
    if [[ $ARG = "-q" ]] || [[ $ARG = "--quiet" ]]; then
        QUIET=1
    elif [[ $ARG = "--doignore" ]] || [[ $ARG = "-i" ]]; then
        DOIGNORE=1
    elif [ -z $REMOTE ]; then
        REMOTE=$ARG
    else
        echo "Usage: $0 [-qi] REMOTE"
        exit 1
    fi
done

if [ $DOIGNORE -eq 1 ]; then
    if [[ -e $GITDIR/.autoUpdateIgnore ]]; then
        IGNORES=$(cat $GITDIR/.autoUpdateIgnore)
    else
        echo -e "\e[31mERROR: Ignore option set, but ignores file does not exist. Continuing without ignoring any repos.\e[m"
    fi
fi

if [[ -n $RSAKEYLOC ]] && [[ $(ssh-add -l) != *"$RSAKEYLOC"* ]]; then
    ssh-add
fi

cd $GITDIR

for FILE in `ls`; do
    if [ -d $FILE ] && [[ -z $(echo $IGNORES | egrep "\b$FILE\b") ]]; then
        cd $FILE
        if [ -e '.git' ] && [[ $(git remote) = *"$REMOTE"* ]]; then
            for BRANCH in `git branch | sed s/"*"//g`; do
                if [ $QUIET -eq 0 ]; then echo "Pushing branch $BRANCH in $FILE."; fi
                OUTPUT=$(git push $REMOTE $BRANCH  2>&1)
                if [ $? -ne 0 ]; then
                    if [ $QUIET -eq 0 ]; then echo -e "\e[31m    ERROR: Pushing of $BRANCH in $FILE to $REMOTE failed.\e[m"; fi
                fi
                if [[ $OUTPUT = *"->"* ]] && [[ $OUTPUT != *"[rejected]"* ]]; then
                    if [ $QUIET -eq 0 ]; then echo -e "\e[36m    Pushed $BRANCH in $FILE to $REMOTE.\e[m"; fi
                fi
            done
        fi
        cd ..
    fi
done

