#!/bin/bash

. $(dirname $0)/scriptsConfig

QUIET=0
NEXTIGNORE=0
IGNORES=""
for ARG in $@; do
    if [ $NEXTIGNORE -eq 1 ]; then
        IGNORES="$IGNORES $ARG"
        NEXTIGNORE=0
    elif [[ $ARG = "-q" ]] || [[ $ARG = "--quiet" ]]; then
        QUIET=1
    elif [[ $ARG = "-i" ]] || [[ $ARG = "--ignore-remote" ]]; then
        NEXTIGNORE=1
    else
        echo "Usage: $0 [-i remote] [-q]"
    fi
done

cd $GITDIR

for FILE in `ls`; do
    if [ -d $FILE ]; then
        cd $FILE
        if [ -e '.git' ]; then
            if [[ -n $RSAKEYLOC ]] && [[ $(ssh-add -l) != *"$HOME/.ssh/id_rsa"* ]]; then
                ssh-add
            fi
            if [ $QUIET -eq 1 ]; then
                git fetch --all --quiet 2>/dev/null
            else
                for REMOTE in `git remote`; do
                    if [[ -z $(echo $IGNORES | egrep "\b$REMOTE\b") ]]; then
                        echo "Fetching remote $REMOTE in $FILE."
                        OUTPUT=$(git fetch $REMOTE 2>&1)
                        if [ $? -ne 0 ]; then
                            echo -e "\e[31m    ERROR: Fetching of $REMOTE in $FILE failed.\e[m"
                        elif [[ $OUTPUT = *"->"*  ]]; then
                            echo -e "\e[36m    Fetched from $REMOTE in $FILE.\e[m"
                        fi
                    fi
                done
            fi
        fi
        cd ..
    fi
done
