#!/bin/bash

QUIET=0
for ARG in $@; do
    if [[ $ARG = "-q" ]] || [[ $ARG = "-quiet" ]]; then
        QUIET=1
    fi  
done

cd ~/git

for FILE in `ls`; do
    if [ -d $FILE ]; then
        cd $FILE
        if [ -e '.git' ]; then
            if [ $QUIET -eq 1 ]; then
                git fetch --all --quiet 2>/dev/null
            else
                for REMOTE in `git remote`; do
                    if [[ $REMOTE = "origin" ]] && [[ $(ssh-add -l) != *"/home/evan1026/.ssh/id_rsa"* ]]; then
                        ssh-add
                    fi
                    echo "Fetching remote $REMOTE in $FILE."
                    OUTPUT=$(git fetch $REMOTE 2>&1)
                    if [ $? -ne 0 ]; then
                        echo -e "\033[31m    ERROR: Fetching of $REMOTE in $FILE failed.\033[m"
                    elif [[ $OUTPUT = *"->"*  ]]; then
                        echo -e "\033[36m    Fetched from $REMOTE in $FILE.\033[m"
                    fi
                done
            fi
        fi
        cd ..
    fi
done
