#!/bin/bash

## -------------------------------------------------------------------
## Keyboard brightness increaser 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Increases screen brightness by 1 (how much that does will vary) (only applies to backlit asus keyboards)
### Usage: keyboardBrightnessUp
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

currBrightness=$(cat /sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight/brightness)

if [[ $currBrightness < 3 ]]; then
    expr $currBrightness + 1 | tee /sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight/brightness
fi
