#!/bin/bash
MPC=$(mpc -h raspberrypi status 2>/dev/null)

if [[ $(echo $MPC | grep -oe "playing")  != "" ]]; then
    mpc -h raspberrypi pause 2>/dev/null
elif [[ $(echo $MPC | grep -oe "paused") != "" ]]; then
    mpc -h raspberrypi play 2>/dev/null
fi
