#!/bin/bash

TIME=$(mpc -h raspberrypi status | grep -oE "[0-9]+\:[0-9]+" | head -n 1)

MIN=$(echo $TIME | grep -oE "[0-9]+" | head -n 1)
SEC=$(echo $TIME | grep -oE "[0-9]+" | tail -n 1)
echo "$MIN $SEC"
if [ $MIN == 0 ] && [ $SEC -lt 5 ]; then
    mpc -h raspberrypi prev
    mpcCurrent
else
    mpc -h raspberrypi prev
    mpc -h raspberrypi next
fi

