#!/bin/bash
## -------------------------------------------------------------------
## Pseudo Working-Line Counter 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Counts how many lines actually do anything in code.
### Works on any language in which an empty line or one containing only curly braces can be considered "non-working".
### Usage: pseudolc [options] <file>...
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

FILES=""
for (( i = 0; i < ${args[<file>,#]}; i++ )); do
    FILES="$FILES ${args[<file>,$i]}"
done

cat $FILES | sed -r "/^\s*\{*\}*\s*$/d" | wc -l

exit 0
