#!/bin/bash

## -------------------------------------------------------------------
## Git Repo Checker 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Replaces tabs with spaces in the given files.
### Usage: replaceTabs [options] <file>...
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

. $(dirname $0)/scriptsConfig

for (( i = 0; i < ${args[<file>,#]}; i++ )); do
    FILE=${args[<file>,$i]}
    cp $FILE $FILE.tmp
    expand -t $TABNUM $FILE.tmp > $FILE
    rm $FILE.tmp
done
