#!/bin/bash

## -------------------------------------------------------------------
## Tmux creater/attacher 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Attaches to the given tmux session, creating it if it doesn't exist.
### Usage: tmuxt [options] <name>
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

if [[ -z $(tmux ls | grep "^${args[<name>]}:") ]]; then
    tmux new -s ${args[<name>]}
else
    tmux at -t ${args[<name>]}
fi

