#!/bin/bash

if [ $(synclient | grep TouchpadOff | sed -r "s/[^01]//g") == 1 ]; then #Touchpad is off, turn it on
    synclient TouchpadOff=0
    notify-send "Touchpad turned on" -t 1500
else
    synclient TouchpadOff=1
    notify-send "Touchpad turned off" -t 1500
fi
