#!/bin/bash

if [[ $(xinput list-props 'ELAN Touchscreen' | grep Enabled | egrep -o "\s+(0|1)$" | sed -r "s/\s+//g") == 0 ]]; then #Touchpad is off, turn it on
    xinput enable 'ELAN Touchscreen'
else
    xinput disable 'ELAN Touchscreen'
fi
