#!/bin/bash

## -------------------------------------------------------------------
## Touchpad enabled status toggler 1.0.0
## 
## This is free software: you are free to change and redistribute it.
## There is NO WARRANTY, to the extent permitted by law.
## -------------------------------------------------------------------

### Toggles whether or not the touchpad is enabled
### Usage: toggleTouchpad
### 
###       -h, --help     Show help options.
###       -v, --version  Print program version.

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(docopts -A args -h "$help" -V "$version" : "$@")"

if [[ $(synclient | grep TouchpadOff | sed -r "s/[^01]//g") == 1 ]]; then #Touchpad is off, turn it on
    synclient TouchpadOff=0
else
    synclient TouchpadOff=1
fi
